---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-merge-conflict

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.11.0-1
  hooks:
  - id: shfmt
    args: [-i, '2', -ci]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint
    args: [--fix]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.135.5
  hooks:
  - id: renovate-config-validator
