---
name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build Pre-configured VDSM Image
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build VDSM image
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
      with:
        timeout_minutes: 60
        max_attempts: 2
        retry_wait_seconds: 60
        command: ./build-image.sh --no-cache
      env:
        REGISTRY: ghcr.io
        DSM_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/vdsm-ci

    - name: Upload videos as artifacts
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: playwright-videos
        path: videos/*.webm
        retention-days: 7
        if-no-files-found: ignore

    - name: Push final image
      if: github.event_name != 'pull_request'
      run: |
        # Source version configuration
        source dsm-version.sh
        docker push ghcr.io/${{ github.repository_owner }}/vdsm-ci:latest
        docker push ghcr.io/${{ github.repository_owner }}/vdsm-ci:${DSM_VERSION}
