---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Run pre-commit checks
      run: |
        nix develop --command pre-commit run --all-files
